# Generated by Django 5.0.14 on 2025-04-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=150)),
                ('long_description', models.CharField(max_length=350)),
                ('date', models.DateField()),
            ],
        ),
    ]
