# Generated by Django 5.0.14 on 2025-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_people_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='people_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
